name: miljohack
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Packages needed or generally handy for project
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # State management
  flutter_bloc: ^7.3.0 # Bloc helper functions
  bloc: ^7.2.0 # Bloc basic state management
  provider: ^6.0.1 # Dependency injection and state management
  equatable: ^2.0.3 # used by bloc for equals & hashcode
  get_it: ^7.2.0 # singleton dependency injection/locator service

  # Images and vectors
  flutter_svg: ^0.22.0 # SVG image support

  # Network communications
  connectivity: ^3.0.6 # Allows check for internet connectivity
  http: ^0.13.4

  # Local storage
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.8

  # Notifications
  flutter_local_notifications: ^9.0.2

  # Firebase related addons
  firebase_core: ^1.8.0 # For Firebase communication, needed for all packages
  firebase_analytics: ^8.3.4 # Google analytics
  firebase_messaging: ^10.0.9 # Notifications
  firebase_crashlytics: ^2.2.4 # Error handling and reporting
  #cloud_firestore: ^2.5.4 # For FireStore communication, database - if we want it

  # Utils
  scroll_to_index: ^2.1.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^1.0.0
  intl_utils: ^2.4.1
  test: ^1.19.3
  mockito: ^5.0.16
  bloc_test: ^8.4.0
  build_runner: ^2.1.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: MiljoHack
      fonts:
        - asset: assets/icons/miljo_hack.ttf
flutter_intl:
  main_locale: en
  enabled: true
