# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    name: MiljøHack2021
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'main'
      - name: Install packages and generate resources
        run: |
          flutter pub get
          flutter doctor -v
          flutter pub run intl_utils:generate && echo "Generated resources"
      #- name: Run tests
      #  run: |
      #    echo ${{ steps.release_log.outputs.release_desc }}
      #    flutter test test/
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install firebase cli
        run: npm install -g firebase-tools
      - name: Install gems
        run: cd android && gem install bundler && bundle install
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: miljøhack2021
          file: app/build/outputs/apk/app.apk